In [ ]:
import numpy as np

In [ ]:
class State_puzzle:
  def __init__(self, state):
    self.state = state
    self.where_is_zero()

  def check(self):
    compare = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 0]])
    comparison = self.state == compare
    return comparison.all()  
  
  def check_moves(self):
    possibles_moves = []
    #Cima é 1, direita é 2, baixo 3 e esquerda 4.
    if( self.column > 0 ):
      possibles_moves.append(4)
    if( self.column < 2 ):
      possibles_moves.append(2)
    if( self.row > 0 ):
      possibles_moves.append(1)
    if( self.row < 2 ):
      possibles_moves.append(3)
    return possibles_moves

  def where_is_zero(self):
    self.row, self.column = np.where( self.state == 0)

  def move(self, position):
    self.where_is_zero()
    move_done = self.state.copy()

    if(position == 1):
      value = move_done[self.row-1, self.column]
      move_done[self.row, self.column] = value
      move_done[self.row-1, self.column] = 0
      
      return move_done
    if(position == 2):
      value = move_done[self.row, self.column+1]
      move_done[self.row, self.column] = value
      move_done[self.row, self.column+1] = 0
      self.column += 1
      
      return move_done
    if(position == 3):
      value = move_done[self.row+1, self.column]
      move_done[self.row, self.column] = value
      move_done[self.row+1, self.column] = 0
      self.row += 1
      
      return move_done
    if(position == 4):
      value = move_done[self.row, self.column-1]
      move_done[self.row, self.column] = value
      move_done[self.row, self.column-1] = 0
      self.column -= 1
      return move_done
    return move_done

  def heuristic_function(self):
    heuristic = 0
    compare = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 0]])
    comparison = compare == self.state
    heuristic = np.count_nonzero(comparison == True)
    return heuristic
    
  

In [ ]:
class Node:
  def __init__(self, state):
    self.state = State_puzzle(state)
    self.heuristic = self.state.heuristic_function()
    self.children = []
  
  def parent_node(self, node):
    self.parent = node
    
  def children_node(self, child):
    self.children.append(child)
  
  

In [ ]:
def visited_node(locked_nodes, node):
    for actual_node in locked_nodes:
      comparison = actual_node == node.state.state
      if comparison.all():
        return True
    return False

In [ ]:
def put_children(node, locked_nodes):
  node.children = []
  moves = node.state.check_moves()
  for move in moves:
    child = node.state.move(move)
    child_node = Node(child)
    if not visited_node(locked_nodes, child_node):
      node.children_node(child_node)
      child_node.parent_node(node)
  return node


In [ ]:
def step_heuristic(node):
  chosen_heuristic = 0
  chosen_node = 0
  for child in node.children:
    if chosen_heuristic < child.heuristic:
      chosen_node = child
      chosen_heuristic = child.heuristic
  
  return chosen_node

In [ ]:
#A*
node = Node(np.array([[4,1,3],[7,2,5],[8,0,6]]))
locked_nodes = []

while not node.state.check():
  locked_nodes.append(node.state.state.copy())
  node = put_children(node, locked_nodes)
  
  if node.children == []:
    node = node.parent
    
  else:
    
    node = step_heuristic(node)
  if node == 0:
    print('Não chegou na resposta')
    break



In [ ]:
print(node.state.state)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


## Discusta sobre o desempenho dos métodos em questões de:


1.   Consumo de memória
2.   Processamento

O algoritmo A* é muito eficiente para solucionar o problema do quebra cabeça deslizante, porém, ele armazena cada nodo passado na memória, se tornando assim menos eficiente para problemas que necessecitem de muitos nodos.


O processamento do algoritmo é bem eficiente, executa em um tempo bem menor do que a maioria dos algoritmos, é conhecido como o melhor algoritmo quando se trata de rapida execução e menor necessidade de expandir nodos.