In [1]:
import numpy as np
import pandas as pd

In [2]:
class Checkers:
  def __init__(self, board):
    self.board = board
    self.player = 1
    self.total_score = self.score(board)

  def score(self, board):
    total_score = 0
    #print(board)
    for i in range(board.shape[0]):
      for j in range(board.shape[1]):
        if board[i, j] == 1:
          total_score += 1
        if board[i, j] == 2:
          total_score += 5
        if board[i, j] == 3:
          total_score -= 1
        if board[i, j] == 4:
          total_score -= 5
    return total_score
  
  def check_victory(self):
    player_1 = 0
    player_2 = 0
    for i in range(board.shape[0]):
      for j in range(board.shape[1]):
        if self.board[i, j] == 1 or self.board[i, j] == 2:
          player_1 += 1
        if self.board[i, j] == 3 or self.board[i, j] == 4:
          player_2 += 1
    return (player_1, player_2)

  def check_moves(self):
    possibles_moves = []
    if self.player == 1:
      for i in range(self.board.shape[0]):
        for j in range(self.board.shape[1]):
          if self.board[i, j] == 1:
            if i>0 and j>0:
              if self.board[i-1, j-1] == 0:
                piece = (i, j)
                new_board = self.board.copy()
                new_board[i, j] = 0
                if i-1 == 0:
                  new_board[i-1, j-1] = 2
                else:
                  new_board[i-1, j-1] = 1
                possibles_moves.append((new_board, self.score(new_board), (i,j)))
            if i>0 and j<5:
              if self.board[i-1, j+1] == 0:
                piece = (i, j)
                new_board = self.board.copy()
                new_board[i, j] = 0
                if i-1 == 0:
                  new_board[i-1, j+1] = 2
                else:
                  new_board[i-1, j+1] = 1
                possibles_moves.append((new_board, self.score(new_board), (i,j)))
            
    if self.player == 2:
      for i in range(self.board.shape[0]):
        for j in range(self.board.shape[1]):
          if self.board[i, j] == 3:
            if i<5 and j>0:
              if self.board[i+1, j-1] == 0:
                piece = (i, j)
                new_board = self.board.copy()
                new_board[i, j] = 0
                if i+1 == 5:
                  new_board[i+1, j-1] = 4
                else:
                  new_board[i+1, j-1] = 3
                possibles_moves.append((new_board, self.score(new_board), (i,j)))
            if i<5 and j<5:
              if self.board[i+1, j+1] == 0:
                piece = (i, j)
                new_board = self.board.copy()
                new_board[i, j] = 0
                if i+1 == 5:
                  new_board[i+1, j+1] = 4
                else:
                  new_board[i+1, j+1] = 3
                possibles_moves.append((new_board, self.score(new_board), (i,j)))
    return possibles_moves
  
  def check(self, board):
    comparison = board == self.board
    return comparison.all()


  def possibles_eat(self):
    possibles = []
    if self.player == 1:
      for i in range(self.board.shape[0]):
        for j in range(self.board.shape[1]):
          if self.board[i, j] == 1:
            aux = self.recursive_eat((i,j), self.board)
            
            if not self.check(aux):
              possibles.append((aux, self.score(aux), (i,j)))
    if self.player == 2:
      for i in range(self.board.shape[0]):
        for j in range(self.board.shape[1]):
          if self.board[i, j] == 3:
            aux = self.recursive_eat((i,j), self.board)
            if not self.check(aux):
              
              possibles.append((aux, self.score(aux), (i,j)))
    return possibles

  def kings_move(self):
    movements = []
    for i in range(self.board.shape[0]):
      for j in range(self.board.shape[1]):
        if self.player == 1:
          if self.board[i, j] == 2:
            lu_list = [(self.board.copy(), self.total_score, (i,j))]
            ru_list = [(self.board.copy(), self.total_score, (i,j))]
            ld_list = [(self.board.copy(), self.total_score, (i,j))]
            rd_list = [(self.board.copy(), self.total_score, (i,j))]

            lu_list = self.kings_move_recursive((i,j), (i,j), lu_list, 'lu')
            ru_list = self.kings_move_recursive((i,j), (i,j), ru_list, 'ru')
            ld_list = self.kings_move_recursive((i,j), (i,j), ld_list, 'ld')
            rd_list = self.kings_move_recursive((i,j), (i,j), rd_list, 'rd')

            movements = lu_list + ru_list + ld_list + rd_list


            return movements
        if self.player == 2:
          if self.board[i, j] == 4:
            lu_list = [(self.board.copy(), self.total_score, (i,j))]
            ru_list = [(self.board.copy(), self.total_score, (i,j))]
            ld_list = [(self.board.copy(), self.total_score, (i,j))]
            rd_list = [(self.board.copy(), self.total_score, (i,j))]

            lu_list = self.kings_move_recursive((i,j), (i,j), lu_list, 'lu')
            ru_list = self.kings_move_recursive((i,j), (i,j), ru_list, 'ru')
            ld_list = self.kings_move_recursive((i,j), (i,j), ld_list, 'ld')
            rd_list = self.kings_move_recursive((i,j), (i,j), rd_list, 'rd')

            movements = lu_list + ru_list + ld_list + rd_list


            return movements
    return movements


  #See what kind of moves the king can do in one direction
  def kings_move_recursive(self, first_position, position, boards, direction):
    i, j = first_position
    k, l = position
    
    actual_board = boards[-1]
    actual_board = actual_board[0]
    

    if direction == 'lu':
      if k>0 and l>0:
        if actual_board[k-1, l-1] == 0:
          new_board = actual_board.copy()
          new_board[i, j] = 0
          new_board[k, l] = 0
          if self.player == 1:
            new_board[k-1, l-1] = 2
          else:
            new_board[k-1, l-1] = 4
          new_score = self.score(new_board)
          boards.append((new_board, new_score, first_position))
          boards = self.kings_move_recursive(first_position, (k-1, l-1), boards, 'lu')
          return boards
        elif k>1 and l>1:
          if actual_board[k-1, l-1] != 0:
            if self.player == 1:
              if actual_board[k-1, l-1] == 3 or actual_board[k-1, l-1] == 4:
                if actual_board[k-2, l-2] == 0:
                  new_board = actual_board.copy()
                  new_board[i, j] = 0
                  new_board[k, l] = 0
                  new_board[k-1, l-1] = 0
                  new_board[k-2, l-2] = 2
                  new_score = self.score(new_board)
                  boards = [(new_board, new_score, first_position)]
                  boards = self.kings_move_recursive(first_position, (k-2, l-2), boards, 'lu')
                  return boards
            if self.player == 2:
              if actual_board[k-1, l-1] == 1 or actual_board[k-1, l-1] == 2:
                if actual_board[k-2, l-2] == 0:
                  new_board = actual_board.copy()
                  new_board[i, j] = 0
                  new_board[k, l] = 0
                  new_board[k-1, l-1] = 0
                  new_board[k-2, l-2] = 4
                  new_score = self.score(new_board)
                  boards = [(new_board, new_score, first_position)]
                  boards = self.kings_move_recursive(first_position, (k-2, l-2), boards, 'lu')
                  return boards

      return boards
    if direction == 'ru':
      if k>0 and l<5:
        if actual_board[k-1, l+1] == 0:
          new_board = actual_board.copy()
          new_board[i, j] = 0
          new_board[k, l] = 0
          if self.player == 1:
            new_board[k-1, l+1] = 2
          else:
            new_board[k-1, l+1] = 4
          new_score = self.score(new_board)
          boards.append((new_board, new_score, first_position))
          boards = self.kings_move_recursive(first_position, (k-1, l+1), boards, 'ru')
          return boards

        elif k>1 and l<4:
          if actual_board[k-1, l+1] != 0:
            if self.player == 1:
              if actual_board[k-1, l+1] == 3 or actual_board[k-1, l+1] == 4:
                if actual_board[k-2, l+2] == 0:
                  new_board = actual_board.copy()
                  new_board[i, j] = 0
                  new_board[k, l] = 0
                  new_board[k-1, l+1] = 0
                  new_board[k-2, l+2] = 2
                  new_score = self.score(new_board)
                  boards = [(new_board, new_score, first_position)]
                  boards = self.kings_move_recursive(first_position, (k-2, l+2), boards, 'ru')
                  return boards
            if self.player == 2:
              if actual_board[k-1, l+1] == 1 or actual_board[k-1, l+1] == 2:
                if actual_board[k-2, l+2] == 0:
                  new_board = actual_board.copy()
                  new_board[i, j] = 0
                  new_board[k, l] = 0
                  new_board[k-1, l+1] = 0
                  new_board[k-2, l+2] = 4
                  new_score = self.score(new_board)
                  boards = [(new_board, new_score, first_position)]
                  boards = self.kings_move_recursive(first_position, (k-2, l+2), boards, 'ru')
                  return boards
      return boards
    if direction == 'ld':
      if k<5 and l>0:
        if actual_board[k+1, l-1] == 0:
          new_board = actual_board.copy()
          new_board[i, j] = 0
          new_board[k, l] = 0
          if self.player == 1:
            new_board[k+1, l-1] = 2
          else:
            new_board[k+1, l-1] = 4
          new_score = self.score(new_board)
          
          boards.append((new_board, new_score, first_position))
          boards = self.kings_move_recursive(first_position, (k+1, l-1), boards, 'ld')
          return boards
        elif k<4 and l>1:
          if actual_board[k+1, l-1] != 0:
            if self.player == 1:
              if actual_board[k+1, l-1] == 3 or actual_board[k+1, l-1] == 4:
                if actual_board[k+2, l-2] == 0:
                  new_board = actual_board.copy()
                  new_board[i, j] = 0
                  new_board[k, l] = 0
                  new_board[k+1, l-1] = 0
                  new_board[k+2, l-2] = 2
                  new_score = self.score(new_board)
                  boards = [(new_board, new_score, first_position)]
                  boards = self.kings_move_recursive(first_position, (k+2, l-2), boards, 'ld')
                  return boards
            if self.player == 2:
              if actual_board[k+1, l-1] == 1 or actual_board[k+1, l-1] == 2:
                if actual_board[k+2, l-2] == 0:
                  new_board = actual_board.copy()
                  new_board[i, j] = 0
                  new_board[k, l] = 0
                  new_board[k+1, l-1] = 0
                  new_board[k+2, l-2] = 4
                  new_score = self.score(new_board)
                  boards = [(new_board, new_score, first_position)]
                  boards = self.kings_move_recursive(first_position, (k+2, l-2), boards, 'ld')
                  return boards
          
      return boards
    if direction == 'rd':
      if k<5 and l<5:
        if actual_board[k+1, l+1] == 0:
          new_board = actual_board.copy()
          new_board[i, j] = 0
          new_board[k, l] = 0
          if self.player == 1:
            new_board[k+1, l+1] = 2
          else:
            new_board[k+1, l+1] = 4
          new_score = self.score(new_board)
          boards.append((new_board, new_score, first_position))
          boards = self.kings_move_recursive(first_position, (k+1, l+1), boards, 'rd')
          return boards
        elif k<5 and l<4:
          if actual_board[k+1, l+1] != 0:
            if self.player == 1:
              if actual_board[k+1, l+1] == 3 or actual_board[k+1, l+1] == 4:
                if actual_board[k+2, l+2] == 0:
                  new_board = actual_board.copy()
                  new_board[i, j] = 0
                  new_board[k, l] = 0
                  new_board[k+1, l+1] = 0
                  new_board[k+2, l+2] = 2
                  new_score = self.score(new_board)
                  boards = [(new_board, new_score, first_position)]
                  boards = self.kings_move_recursive(first_position, (k+2, l+2), boards, 'rd')
                  return boards
            if self.player == 2:
              if actual_board[k+1, l+1] == 1 or actual_board[k+1, l+1] == 2:
                if actual_board[k+2, l+2] == 0:
                  new_board = actual_board.copy()
                  new_board[i, j] = 0
                  new_board[k, l] = 0
                  new_board[k+1, l+1] = 0
                  new_board[k+2, l+2] = 4
                  new_score = self.score(new_board)
                  boards = [(new_board, new_score, first_position)]
                  boards = self.kings_move_recursive(first_position, (k+2, l+2), boards, 'rd')
                  return boards
      return boards



  def recursive_eat(self, position, board):
    i, j = position
    if self.player == 1:
      if board[i, j] == 1:
            if i>1 and j>1:
              if board[i-1, j-1] == 3 or board[i-1, j-1] == 4:
                if board[i-2,j-2] == 0:
                  new_board = board.copy()
                  new_board[i, j] = 0
                  new_board[i-1, j-1] = 0
                  if i-2 == 0:
                    new_board[i-2, j-2] = 2
                  else:
                    new_board[i-2, j-2] = 1
                  
                  return self.recursive_eat((i-2, j-2), new_board)

              
            if i>1 and j<4:
              if board[i-1, j+1] == 3 or board[i-1, j+1] == 4:
                if board[i-2, j+2] == 0:
                  new_board = board.copy()
                  new_board[i, j] = 0
                  new_board[i-1, j+1] = 0
                  if i-2 == 0:
                    new_board[i-2, j+2] = 2
                  else:
                    new_board[i-2, j+2] = 1

                  return self.recursive_eat((i-2, j+2), new_board)
            
      return board.copy()
    if self.player == 2:
      if board[i, j] == 3:
          if i<4 and j>1:
            if board[i+1, j-1] == 1 or board[i+1, j-1] == 2:
              if board[i+2, j-2] == 0:
                new_board = board.copy()
                new_board[i, j] = 0
                new_board[i+1, j-1] = 0
                if i+2 == 5:
                  new_board[i+2, j-2] = 4
                else:
                  new_board[i+2, j-2] = 3
                
                return self.recursive_eat((i+2, j-2), new_board)

          if i<4 and j<4:
            if board[i+1, j+1] == 1 or board[i+1, j+1] == 2:
              if board[i+2, j+2] == 0:
                new_board = board.copy()
                new_board[i, j] = 0
                new_board[i+1, j+1] = 0
                if i+2 == 5:
                  new_board[i+2, j+2] = 4
                else:
                  new_board[i+2, j+2] = 3
                
                return self.recursive_eat((i+2, j+2), new_board)
          
          
      return board.copy()
  
  def all_possibles_moves(self):
    all_moves = []
    if self.possibles_eat() == []:
      all_moves += self.kings_move()
      all_moves += self.check_moves()
      return all_moves
    else:
      all_moves += self.kings_move()
      all_moves += self.possibles_eat()
      return all_moves

In [3]:
board = np.array([[3, 0, 3, 0, 3, 0],
                  [0, 3, 0, 3, 0, 3],
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 1, 0, 1],
                  [1, 0, 1, 0, 1, 0]])
board = np.array([[3, 0, 3, 0, 0, 0],
                  [0, 3, 0, 1, 0, 3],
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 1, 0, 1],
                  [1, 0, 1, 0, 1, 0]])
checkers = Checkers(board)
checkers.player = 1
#checkers.possibles_eat()
#checkers.kings_move()
#checkers.check_moves()
#checkers.check_victory()
#checkers.all_possibles_moves()

In [4]:
def higher(checkers):
  higher_score = checkers[0]
  for checker in checkers:
    if higher_score.total_score < checker.total_score:
      higher_score = checker
  return higher_score

In [5]:
def lower(checkers):
  lower_score = checkers[0]
  for checker in checkers:
    if lower_score.total_score > checker.total_score:
      lower_score = checker
  return lower_score

In [6]:
#minimax
def minimax(checker, deep_max, i, player):
  best_score = checker.total_score
  best_move = checker
  if i < deep_max:
    moves = checker.all_possibles_moves()
    all_checkers = []
    for move in moves:
      prox_move, prox_score, changes = move
      aux_move = Checkers(prox_move)
      if player == 1:
        aux_move.player = 2
        j = i + 1
        aux, aux_checker = minimax(aux_move, deep_max, j, aux_move.player)
        if best_score <= aux:
          best_score = aux
          best_move = aux_move
      else:
        aux_move.player = 1
        j = i + 1
        
        aux, aux_checker = minimax(aux_move, deep_max, j, aux_move.player)
        if best_score >= aux:
          best_score = aux
          best_move = aux_move
      
    
    return best_score, best_move
  else:
    return checker.total_score, checker


In [7]:
board = np.array([[3, 0, 3, 0, 3, 0],
                  [0, 3, 0, 3, 0, 3],
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [1, 0, 1, 0, 1, 0],
                  [0, 1, 0, 1, 0, 1]])
checker_game = Checkers(board)
checker_game.player = 1
check1, check2 = checker_game.check_victory()
while check1 != 0 and check2 != 0:
  if checker_game.player == 1:
    _, checker_game = minimax(checker_game, 4, 0, 1)
    checker_game.player = 2
  else:
    _, checker_game = minimax(checker_game, 4, 0, 2)
    checker_game.player = 1
  check1, check2 = checker_game.check_victory()

  print(checker_game.board)

[[3 0 3 0 3 0]
 [0 3 0 3 0 3]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 1]]
[[3 0 3 0 3 0]
 [0 3 0 3 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 1]]
[[3 0 3 0 3 0]
 [0 3 0 3 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 0]]
[[3 0 3 0 3 0]
 [0 3 0 0 0 0]
 [0 0 3 0 3 0]
 [0 0 0 0 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 0]]
[[3 0 3 0 3 0]
 [0 3 0 1 0 0]
 [0 0 3 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 1 0]
 [0 1 0 1 0 0]]
[[3 0 0 0 3 0]
 [0 3 0 0 0 0]
 [0 0 3 0 3 0]
 [0 0 0 0 0 0]
 [1 0 1 0 1 0]
 [0 1 0 1 0 0]]
[[3 0 0 0 3 0]
 [0 3 0 0 0 0]
 [0 0 3 0 3 0]
 [0 0 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]]
[[3 0 0 0 0 0]
 [0 3 0 3 0 0]
 [0 0 3 0 3 0]
 [0 0 0 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]]
[[3 0 0 0 0 0]
 [0 3 0 3 0 0]
 [0 0 3 0 3 0]
 [0 0 0 0 0 1]
 [1 0 1 0 1 0]
 [0 1 0 0 0 0]]
[[3 0 0 0 0 0]
 [0 0 0 3 0 0]
 [3 0 3 0 3 0]
 [0 0 0 0 0 1]
 [1 0 1 0 1 0]
 [0 1 0 0 0 0]]
[[3 0 0 0 0 0]
 [0 0 0 3 0 0]
 [3 0 3 0 3 0]
 [0 0 0 1 0 1]
 [1 0 0 0 1 0]
 [0 1 0 0 0 0]]